<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsAuthorization\Controller\AdminController'                        => __DIR__ . '/src/Controller/AdminController.php',
    'CmsAuthorization\Controller\RoleController'                         => __DIR__ . '/src/Controller/RoleController.php',
    'CmsAuthorization\Entity\Repository\RoleRepository'                  => __DIR__ . '/src/Entity/Repository/RoleRepository.php',
    'CmsAuthorization\Entity\Role'                                       => __DIR__ . '/src/Entity/Role.php',
    'CmsAuthorization\Factory\ModuleOptionsFactory'                      => __DIR__ . '/src/Factory/ModuleOptionsFactory.php',
    'CmsAuthorization\Factory\View\Strategy\RedirectStrategyFactory'     => __DIR__ . '/src/Factory/View/Strategy/RedirectStrategyFactory.php',
    'CmsAuthorization\Factory\View\Strategy\UnauthorizedStrategyFactory' => __DIR__ . '/src/Factory/View/Strategy/UnauthorizedStrategyFactory.php',
    'CmsAuthorization\Identity\IdentityInterface'                        => __DIR__ . '/src/Identity/IdentityInterface.php',
    'CmsAuthorization\Mapping\RoleableInterface'                         => __DIR__ . '/src/Mapping/RoleableInterface.php',
    'CmsAuthorization\Mapping\RoleInterface'                             => __DIR__ . '/src/Mapping/RoleInterface.php',
    'CmsAuthorization\Mapping\Traits\RoleableTrait'                      => __DIR__ . '/src/Mapping/Traits/RoleableTrait.php',
    'CmsAuthorization\Module'                                            => __DIR__ . '/src/Module.php',
    'CmsAuthorization\Options\ModuleOptions'                             => __DIR__ . '/src/Options/ModuleOptions.php',
    'CmsAuthorization\Options\ModuleOptionsInterface'                    => __DIR__ . '/src/Options/ModuleOptionsInterface.php',
    'CmsAuthorization\Persistence\RoleMapperInterface'                   => __DIR__ . '/src/Persistence/RoleMapperInterface.php',
    'CmsAuthorization\View\Strategy\AbstractStrategy'                    => __DIR__ . '/src/View/Strategy/AbstractStrategy.php',
    'CmsAuthorization\View\Strategy\RedirectStrategy'                    => __DIR__ . '/src/View/Strategy/RedirectStrategy.php',
    'CmsAuthorization\View\Strategy\UnauthorizedStrategy'                => __DIR__ . '/src/View/Strategy/UnauthorizedStrategy.php',
    'CmsAuthorizationTest\Framework\TestCase'                            => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsAuthorizationTest\SampleTest'                                    => __DIR__ . '/tests/SampleTest.php',
);
