<?php
/**
 * CoolMS2 Authorization Module (http://www.coolms.com/)
 *
 * @link        http://github.com/coolms/authorization for the canonical source repository
 * @copyright   Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license     http://www.coolms.com/license/new-bsd New BSD License
 * @author      Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsAuthorization;

?>

<h1>403 Forbidden</h1>
<p>
<?php if ($this->route): ?>
    You are not authorized to access <?= $this->route ?>.
<?php elseif ($this->controller): ?>
    You are not authorized to access
    <?= $this->controller ?><?php if ($this->action): ?>::<?= $this->action ?>Action()<?php endif; ?>.
<?php elseif ($this->error === 'error-unauthorized'): ?>
    You are not authorized <?= $this->exception->getMessage() ?>.
<?php else: ?>
    An unknown error occurred.
<?php endif; ?>
</p>
